#!/bin/bash

# Copyright (C) Harsh Shandilya <msfjarvis@gmail.com>
# SPDX-License-Identifier: GPL-3.0-only
# This script is basically the README from algo in a script to avoid copypasta.

cd "${HOME}/git-repos/algo/"
apt update
apt install build-essential libssl-dev libffi-dev python python-dev python-pip python-setuptools python-virtualenv zip unzip -y
python -m virtualenv --python="$(which python2)" env && source env/bin/activate && python -m pip install -U pip && python -m pip install -r requirements.txt
./algo
CUR_DIR=$(pwd)
CONFIG_DIR=$(find configs -maxdepth 1 -type d | grep '/')
if [ -d "${CONFIG_DIR}"/wireguard/ ]; then
    cd "${CONFIG_DIR}"/wireguard/
    zip -u "${CUR_DIR}"/wg-configs.zip ./*.conf
    cd "${CUR_DIR}"
fi